version: '3'
services:
  express-app:
    build: 
      context: ./backend
    container_name: express-app
    ports:
      - "3005:3005"
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: express-api
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  admin:
    build:
      context: ./admin
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  mongo_data:
  
networks:
  app-network:
    driver: bridge
